pipeline {
    agent any
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_HUB_CREDS = credentials('docker-hub-credentials') // Update this ID to match your Jenkins credentials
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker') {
            steps {
                sh """
                    echo 'Building Docker Image'
                    docker build -t abhishekf5/cicd-e2e:${IMAGE_TAG} .
                """
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh """
                            echo '${DOCKER_PASSWORD}' | docker login -u '${DOCKER_USERNAME}' --password-stdin
                            docker push abhishekf5/cicd-e2e:${IMAGE_TAG}
                            docker logout
                        """
                    }
                }
            }
        }
        
        stage('Update K8S Manifests') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh """
                            git clone https://github.com/iam-veeramalla/cicd-demo-manifests-repo.git
                            cd cicd-demo-manifests-repo
                            git config user.email "jenkins@example.com"
                            git config user.name "Jenkins Pipeline"
                            
                            sed -i "s|:32|:${IMAGE_TAG}|g" deploy.yaml
                            
                            git add deploy.yaml
                            git commit -m "Updated deployment to version ${IMAGE_TAG}"
                            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/iam-veeramalla/cicd-demo-manifests-repo.git HEAD:main
                        """
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
